### PR TITLE
change url, fixes curl error

### PR DESCRIPTION
**Pull request by eltrevii**

### CODE REVIEW

**Comment by RadNotRed** [comment]
Until they fix this, I updated my branch, forgot to change it back before releasing... Was using old tweaked drivers because of the un-updated link.

**Review by RadNotRed — APPROVED** [review]
Good.

**Review by RadNotRed — COMMENTED** [review]
I lied... This seems to be a curl issue.

**Comment by eltrevii** [comment]
@RadNotRed wdym curl issue?

**Comment by RadNotRed** [comment]
> @RadNotRed wdym curl issue?

Some people have issues with the way the curl is formatted in the program

**Comment by eltrevii** [comment]
oh ok

**Review by JonathahWasTaken — APPROVED** [review]

**Pull request merged**
